In [1]:
import os
print(os.getcwd())

C:\Users\91917\Delivery_Time_Prediction

In [2]:
import pandas as pd

df = pd.read_csv("Food_Delivery_Times.csv")
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [3]:
df.columns

Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

In [5]:
df.tail()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
995,107,8.50,Clear,High,Evening,Car,13,3.0,54
996,271,16.28,Rainy,Low,Morning,Scooter,8,9.0,71
997,861,15.62,Snowy,High,Evening,Scooter,26,2.0,81
998,436,14.17,Clear,Low,Afternoon,Bike,8,0.0,55
999,103,6.63,Foggy,Low,Night,Scooter,24,3.0,58

In [7]:
df.dropna(inplace=True)

y = df['Delivery_Time_min']

X = df.drop('Delivery_Time_min', axis=1)

X = X.drop('Order_ID', axis=1)

X = pd.get_dummies(X)

df = pd.concat([X, y], axis=1)

In [8]:
df.count()

Distance_km               883
Preparation_Time_min      883
Courier_Experience_yrs    883
Weather_Clear             883
Weather_Foggy             883
Weather_Rainy             883
Weather_Snowy             883
Weather_Windy             883
Traffic_Level_High        883
Traffic_Level_Low         883
Traffic_Level_Medium      883
Time_of_Day_Afternoon     883
Time_of_Day_Evening       883
Time_of_Day_Morning       883
Time_of_Day_Night         883
Vehicle_Type_Bike         883
Vehicle_Type_Car          883
Vehicle_Type_Scooter      883
Delivery_Time_min         883
dtype: int64

In [9]:
df.isnull().sum()

Distance_km               0
Preparation_Time_min      0
Courier_Experience_yrs    0
Weather_Clear             0
Weather_Foggy             0
Weather_Rainy             0
Weather_Snowy             0
Weather_Windy             0
Traffic_Level_High        0
Traffic_Level_Low         0
Traffic_Level_Medium      0
Time_of_Day_Afternoon     0
Time_of_Day_Evening       0
Time_of_Day_Morning       0
Time_of_Day_Night         0
Vehicle_Type_Bike         0
Vehicle_Type_Car          0
Vehicle_Type_Scooter      0
Delivery_Time_min         0
dtype: int64

In [10]:
X = pd.get_dummies(X, drop_first=True)

In [11]:
X.head()

,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Weather_Clear,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Windy,Traffic_Level_High,Traffic_Level_Low,Traffic_Level_Medium,Time_of_Day_Afternoon,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Vehicle_Type_Bike,Vehicle_Type_Car,Vehicle_Type_Scooter
0,7.93,12,1.0,False,False,False,False,True,False,True,False,True,False,False,False,False,False,True
1,16.42,20,2.0,True,False,False,False,False,False,False,True,False,True,False,False,True,False,False
2,9.52,28,1.0,False,True,False,False,False,False,True,False,False,False,False,True,False,False,True
3,7.44,5,1.0,False,False,True,False,False,False,False,True,True,False,False,False,False,False,True
4,19.03,16,5.0,True,False,False,False,False,False,True,False,False,False,True,False,True,False,False

In [12]:
X.columns

Index(['Distance_km', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Weather_Clear', 'Weather_Foggy', 'Weather_Rainy', 'Weather_Snowy',
       'Weather_Windy', 'Traffic_Level_High', 'Traffic_Level_Low',
       'Traffic_Level_Medium', 'Time_of_Day_Afternoon', 'Time_of_Day_Evening',
       'Time_of_Day_Morning', 'Time_of_Day_Night', 'Vehicle_Type_Bike',
       'Vehicle_Type_Car', 'Vehicle_Type_Scooter'],
      dtype='object')

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(max_depth=10)
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=10)

In [15]:
y_pred = model.predict(X_test)

In [16]:
from sklearn.metrics import r2_score

print("Accuracy:", r2_score(y_test, y_pred))

Accuracy: 0.4006500965443045

In [17]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=15,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

In [18]:
from sklearn.metrics import r2_score

print("Random Forest Accuracy:", r2_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.7668731195842867

In [19]:
import pandas as pd

df = pd.read_csv("Food_Delivery_Times.csv")
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

rf = RandomForestRegressor(n_estimators=100, max_depth=15)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

In [21]:
from sklearn.metrics import r2_score

print("New Accuracy:", r2_score(y_test, y_pred_rf))

New Accuracy: 0.7207545546431997

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=20,
    random_state=42
)

# Train
rf.fit(X_train, y_train)

# Predict
y_pred_rf = rf.predict(X_test)

# Evaluate
print("R2 Score:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))

R2 Score: 0.7638490145897701
MAE: 6.8462429378531064

In [23]:
import pickle

pickle.dump(rf, open("delivery_model.pkl", "wb"))
pickle.dump(X.columns, open("columns.pkl", "wb"))

In [24]:
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68